version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - ./storage/postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "PASSWORD"
      POSTGRES_DB: "redmine"
      PGDATA: "/var/lib/postgresql/data"
    restart: always

  redmine:
    image: redmine:latest
    container_name: redmine
    ports:
      - "8080:3000"
    volumes:
      - ./storage/redmine-plugins:/usr/src/redmine/plugins
      - ./storage/redmine-themes:/usr/src/redmine/public/themes
      - ./storage/redmine-data:/usr/src/redmine/files
      - ./storage/gitea:/data
    environment:
      REDMINE_DB_POSTGRES: "postgres"
      REDMINE_DB_USERNAME: "postgres"
      REDMINE_DB_PASSWORD: "PASSWORD"
      REDMINE_DB_DATABASE: "redmine"
    restart: always
    depends_on:
      - postgres

  db-init:
    image: postgres:13
    container_name: db-init
    depends_on:
      - postgres
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/gitea-init.sql:ro
    entrypoint: >
      bash -c "
        echo '⏳ Waiting for PostgreSQL...' &&
        for i in {1..30}; do
          pg_isready -h postgres -U postgres && break;
          echo 'Waiting...';
          sleep 1;
        done &&
        echo '✅ PostgreSQL is ready, executing SQL...' &&
        psql -h postgres -U postgres -w -f /docker-entrypoint-initdb.d/gitea-init.sql
      "
    environment:
      PGPASSWORD: "PASSWORD"
    restart: "no"

  gitea:
    image: docker.gitea.com/gitea:1.23.8
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
#      - GIT_CONFIG_REDMINE_HOST=http://localhost:8080
#      - GIT_CONFIG_REDMINE_APIKEY=68a324d21a5d28205139ea49e96aa36f263eb1f1
    volumes:
      - ./storage/gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    restart: always
#    command: /bin/sh -c "apk add --no-cache python3 bash && /app/gitea/gitea web"
    depends_on:
      - postgres
      - db-init

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    environment:
      MM_DBTYPE: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable
    volumes:
      - ./storage/mattermost:/mattermost/data
    ports:
      - "8065:8065"
    restart: always
    depends_on:
      - postgres
      - db-init
